/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.mhs.qsol.queryparser;

public interface QueryParserConstants {

  int EOF = 0;
  int ESCAPED = 6;
  int NON_ESCAPED = 7;
  int ANY_TOKEN = 8;
  int AND = 9;
  int OR = 10;
  int ANDNOT = 11;
  int PROXIMITY = 12;
  int MATCHALL = 13;
  int QUOTED = 14;
  int BOOSTEDQUOTED = 15;
  int FUZZY = 16;
  int RANGE = 17;
  int FIELDSTART = 18;
  int BOOSTEDSEARCHTOKEN = 19;
  int SEARCHTOKEN = 20;
  int WILDCARD = 21;
  int OP1 = 22;
  int OP2 = 23;
  int OP3 = 24;
  int OP4 = 25;
  int LETTER = 26;
  int DIGIT = 27;

  int DEFAULT = 0;

  String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
      "\"\\f\"", "<ESCAPED>", "<NON_ESCAPED>", "<ANY_TOKEN>", "\"&\"", "<OR>",
      "<ANDNOT>", "<PROXIMITY>", "\"*:*\"", "<QUOTED>", "<BOOSTEDQUOTED>",
      "<FUZZY>", "<RANGE>", "<FIELDSTART>", "<BOOSTEDSEARCHTOKEN>",
      "<SEARCHTOKEN>", "<WILDCARD>", "\"op1\"", "\"op2\"", "\"op3\"",
      "\"op4\"", "<LETTER>", "<DIGIT>", "\")\"", "\"(\"", };

}
