//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.visitor;

import com.mhs.qsol.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
  //
  // Auto class visitors--probably don't need to be overridden.
  //
  public void visit(NodeList n) {
    for (Enumeration<Node> e = n.elements(); e.hasMoreElements();)
      e.nextElement().accept(this);
  }

  public void visit(NodeListOptional n) {
    if (n.present())
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();)
        e.nextElement().accept(this);
  }

  public void visit(NodeOptional n) {
    if (n.present())
      n.node.accept(this);
  }

  public void visit(NodeSequence n) {
    for (Enumeration<Node> e = n.elements(); e.hasMoreElements();)
      e.nextElement().accept(this);
  }

  public void visit(NodeToken n) {
  }

  //
  // User-generated visitor methods below
  //

  /**
   * f0 -> CheckOrd1Search() f1 -> <EOF>
   */
  public void visit(Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  /**
   * f0 -> CheckOrd2Search() f1 -> ( Ord1Search() )?
   */
  public void visit(CheckOrd1Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  /**
   * f0 -> <OP1> f1 -> CheckOrd2Search() f2 -> ( Ord1Search() )?
   */
  public void visit(Ord1Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> CheckOrd3Search() f1 -> ( Ord2Search() )?
   */
  public void visit(CheckOrd2Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  /**
   * f0 -> <OP2> f1 -> CheckOrd3Search() f2 -> ( Ord2Search() )?
   */
  public void visit(Ord2Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> CheckOrd4Search() f1 -> ( Ord3Search() )?
   */
  public void visit(CheckOrd3Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  /**
   * f0 -> <OP3> f1 -> CheckOrd4Search() f2 -> ( Ord3Search() )?
   */
  public void visit(Ord3Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> BasicSearch() f1 -> ( Ord4Search() )?
   */
  public void visit(CheckOrd4Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  /**
   * f0 -> <OP4> f1 -> BasicSearch() f2 -> ( Ord4Search() )?
   */
  public void visit(Ord4Search n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> <FIELDSTART> f1 -> CheckOrd1Search() f2 -> ")"
   */
  public void visit(FieldSearch n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> <MATCHALL> | <QUOTED> | <BOOSTEDQUOTED> | <RANGE> | <WILDCARD> |
   * <FUZZY> | <BOOSTEDSEARCHTOKEN> | <SEARCHTOKEN>
   */
  public void visit(SearchToken n) {
    n.f0.accept(this);
  }

  /**
   * f0 -> "(" f1 -> CheckOrd1Search() f2 -> ")"
   */
  public void visit(ParenthesisSearch n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  /**
   * f0 -> ( BasicSearchType() )+
   */
  public void visit(BasicSearch n) {
    n.f0.accept(this);
  }

  /**
   * f0 -> FieldSearch() | SearchToken() | ParenthesisSearch()
   */
  public void visit(BasicSearchType n) {
    n.f0.accept(this);
  }

}
