//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.visitor;

import com.mhs.qsol.syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

  //
  // void Auto class visitors
  //

  public void visit(NodeList n);

  public void visit(NodeListOptional n);

  public void visit(NodeOptional n);

  public void visit(NodeSequence n);

  public void visit(NodeToken n);

  //
  // User-generated visitor methods below
  //

  /**
   * f0 -> CheckOrd1Search() f1 -> <EOF>
   */
  public void visit(Search n);

  /**
   * f0 -> CheckOrd2Search() f1 -> ( Ord1Search() )?
   */
  public void visit(CheckOrd1Search n);

  /**
   * f0 -> <OP1> f1 -> CheckOrd2Search() f2 -> ( Ord1Search() )?
   */
  public void visit(Ord1Search n);

  /**
   * f0 -> CheckOrd3Search() f1 -> ( Ord2Search() )?
   */
  public void visit(CheckOrd2Search n);

  /**
   * f0 -> <OP2> f1 -> CheckOrd3Search() f2 -> ( Ord2Search() )?
   */
  public void visit(Ord2Search n);

  /**
   * f0 -> CheckOrd4Search() f1 -> ( Ord3Search() )?
   */
  public void visit(CheckOrd3Search n);

  /**
   * f0 -> <OP3> f1 -> CheckOrd4Search() f2 -> ( Ord3Search() )?
   */
  public void visit(Ord3Search n);

  /**
   * f0 -> BasicSearch() f1 -> ( Ord4Search() )?
   */
  public void visit(CheckOrd4Search n);

  /**
   * f0 -> <OP4> f1 -> BasicSearch() f2 -> ( Ord4Search() )?
   */
  public void visit(Ord4Search n);

  /**
   * f0 -> <FIELDSTART> f1 -> CheckOrd1Search() f2 -> ")"
   */
  public void visit(FieldSearch n);

  /**
   * f0 -> <MATCHALL> | <QUOTED> | <BOOSTEDQUOTED> | <RANGE> | <WILDCARD> |
   * <FUZZY> | <BOOSTEDSEARCHTOKEN> | <SEARCHTOKEN>
   */
  public void visit(SearchToken n);

  /**
   * f0 -> "(" f1 -> CheckOrd1Search() f2 -> ")"
   */
  public void visit(ParenthesisSearch n);

  /**
   * f0 -> ( BasicSearchType() )+
   */
  public void visit(BasicSearch n);

  /**
   * f0 -> FieldSearch() | SearchToken() | ParenthesisSearch()
   */
  public void visit(BasicSearchType n);

}
