//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
  public void accept(com.mhs.qsol.visitor.Visitor v);

  public <R, A> R accept(com.mhs.qsol.visitor.GJVisitor<R, A> v, A argu);

  public <R> R accept(com.mhs.qsol.visitor.GJNoArguVisitor<R> v);

  public <A> void accept(com.mhs.qsol.visitor.GJVoidVisitor<A> v, A argu);
}
