//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.syntaxtree;

/**
 * Grammar production: f0 -> <OP3> f1 -> CheckOrd4Search() f2 -> ( Ord3Search()
 * )?
 */
public class Ord3Search implements Node {
  public NodeToken f0;
  public CheckOrd4Search f1;
  public NodeOptional f2;

  public Ord3Search(NodeToken n0, CheckOrd4Search n1, NodeOptional n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public Ord3Search(CheckOrd4Search n0, NodeOptional n1) {
    f0 = new NodeToken("op3");
    f1 = n0;
    f2 = n1;
  }

  public void accept(com.mhs.qsol.visitor.Visitor v) {
    v.visit(this);
  }

  public <R, A> R accept(com.mhs.qsol.visitor.GJVisitor<R, A> v, A argu) {
    return v.visit(this, argu);
  }

  public <R> R accept(com.mhs.qsol.visitor.GJNoArguVisitor<R> v) {
    return v.visit(this);
  }

  public <A> void accept(com.mhs.qsol.visitor.GJVoidVisitor<A> v, A argu) {
    v.visit(this, argu);
  }
}
