//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.syntaxtree;

/**
 * Grammar production: f0 -> <OP4> f1 -> BasicSearch() f2 -> ( Ord4Search() )?
 */
public class Ord4Search implements Node {
  public NodeToken f0;
  public BasicSearch f1;
  public NodeOptional f2;

  public Ord4Search(NodeToken n0, BasicSearch n1, NodeOptional n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public Ord4Search(BasicSearch n0, NodeOptional n1) {
    f0 = new NodeToken("op4");
    f1 = n0;
    f2 = n1;
  }

  public void accept(com.mhs.qsol.visitor.Visitor v) {
    v.visit(this);
  }

  public <R, A> R accept(com.mhs.qsol.visitor.GJVisitor<R, A> v, A argu) {
    return v.visit(this, argu);
  }

  public <R> R accept(com.mhs.qsol.visitor.GJNoArguVisitor<R> v) {
    return v.visit(this);
  }

  public <A> void accept(com.mhs.qsol.visitor.GJVoidVisitor<A> v, A argu) {
    v.visit(this, argu);
  }
}
