//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.syntaxtree;

/**
 * Grammar production: f0 -> "(" f1 -> CheckOrd1Search() f2 -> ")"
 */
public class ParenthesisSearch implements Node {
  public NodeToken f0;
  public CheckOrd1Search f1;
  public NodeToken f2;

  public ParenthesisSearch(NodeToken n0, CheckOrd1Search n1, NodeToken n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public ParenthesisSearch(CheckOrd1Search n0) {
    f0 = new NodeToken("(");
    f1 = n0;
    f2 = new NodeToken(")");
  }

  public void accept(com.mhs.qsol.visitor.Visitor v) {
    v.visit(this);
  }

  public <R, A> R accept(com.mhs.qsol.visitor.GJVisitor<R, A> v, A argu) {
    return v.visit(this, argu);
  }

  public <R> R accept(com.mhs.qsol.visitor.GJNoArguVisitor<R> v) {
    return v.visit(this);
  }

  public <A> void accept(com.mhs.qsol.visitor.GJVoidVisitor<A> v, A argu) {
    v.visit(this, argu);
  }
}
