//
// Generated by JTB 1.3.2
//

package com.mhs.qsol.syntaxtree;

/**
 * Grammar production: f0 -> CheckOrd1Search() f1 -> <EOF>
 */
public class Search implements Node {
  public CheckOrd1Search f0;
  public NodeToken f1;

  public Search(CheckOrd1Search n0, NodeToken n1) {
    f0 = n0;
    f1 = n1;
  }

  public Search(CheckOrd1Search n0) {
    f0 = n0;
    f1 = new NodeToken("");
  }

  public void accept(com.mhs.qsol.visitor.Visitor v) {
    v.visit(this);
  }

  public <R, A> R accept(com.mhs.qsol.visitor.GJVisitor<R, A> v, A argu) {
    return v.visit(this, argu);
  }

  public <R> R accept(com.mhs.qsol.visitor.GJNoArguVisitor<R> v) {
    return v.visit(this);
  }

  public <A> void accept(com.mhs.qsol.visitor.GJVoidVisitor<A> v, A argu) {
    v.visit(this, argu);
  }
}
